display_errors = On
display_startup_errors = On
error_reporting = E_ALL
log_errors = On
html_errors = On

; Limites assouplies pour le dev (upload d'images de projets, etc.)
upload_max_filesize = 128M
post_max_size = 128M
memory_limit = 256M

; Sessions
session.gc_maxlifetime = 86400
